### ISSUE TITLE
DB Config via env variables

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nfldb#5]
Currently configuring the db connection requires an ini file.  I would like env variables to override these settings.

**Comment by mtong0505** [comment]
Hi, Derek,

As in the ini file, do I need to change any of these settings?

# The username and password for the database specified above.
# The user should have permission to add, delete and remove data.
# Also, the user should have permission to create/alter/drop tables,
# indexes and types.
user = postgres
password = postgres

# The host of the PostgreSQL server. When using a local database, this should
# be set to "localhost".
 host = postgres

 Thanks.

**Comment by derek-adair** [comment]
If you're running the docker-compose example, yes.

**Comment by mtong0505** [comment]
Actually I'm on windows. I used the windows installation guide and it's working .

Thanks anyway.

**Comment by derek-adair** [comment]
@mtong0505 I'm ocd about my issues.  SUPER glad windows guide worked.  Come join me in [discord](https://discord.gg/G7uay2) if you have any issues.  I think some of the newer data may be corrupted and/or incomplete.

**Comment by mtong0505** [comment]
Yes. Some error showed at the end of nfldb-update. 

How shall I add you on discord?
